#!/bin/bash
#
# Copyright (C) 2004-2008 Centro de Computacao Cientifica e Software Livre
# Departamento de Informatica - Universidade Federal do Parana - C3SL/UFPR
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,
# USA.
 
 
#**********************************
#
#  Script Version: 1.0.0
#                  24/03/2008
#  Dependencies:
#       mdm-path.inc
#       mdm-debug.inc
#       mdm-hardware.inc
#       mdm-links.inc
#       mdm-images.inc
#       mdm-execute.inc
#       mdm-xephyr-loader (not sourced)
#       mdm-conf

 # diretório que contém os arquivos inclusos
 INCLUDE=/usr/share/mdm/include
 
 export TEXTDOMAINDIR=/usr/share/locale
 export TEXTDOMAIN=multiseat-xephyr

 source ${INCLUDE}/mdm-debug.inc
 source ${INCLUDE}/mdm-path.inc
 source ${INCLUDE}/mdm-hardware.inc
 source ${INCLUDE}/mdm-images.inc
  
 source ${CONFIG_FILE}
 source ${INCLUDE}/mdm-links.inc
 source ${INCLUDE}/mdm-execute.inc

function Main()
{
    local TERMINAL=${1}
    
    OpenTerminal ${TERMINAL}
    
}

# Start

    Main $@
    
    exit 0
    
