#! /bin/bash
#
# Copyright (C) 2004-2008 Centro de Computacao Cientifica e Software Livre
# Departamento de Informatica - Universidade Federal do Parana - C3SL/UFPR
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,
# USA.

#  The function of this script is to load Xephyr. It may be called
#  to do one of two functions:
#       * call directly the script that calls Xephyr
#       * call indirectly the script that calls Xephyr, throught the
#         OpenTerminal function. This resource is used because is necessary
#         to keep a script running in background for each one of the seat 
#         heads. To more information, see OpenTerminal function on 
#         mdm-execute.inc file
#

#**********************************
#  Script Version: 1.0.1
#                  27/02/2008
#
#  Dependencies:
#       mdm-path.inc
#       mdm-debug.inc
#       mdm-images.inc
#       mdm-execute.inc
#       mdm-xephyr.inc
#       mdm-links.inc
#       mdm.conf
 
 INCLUDE=/usr/share/mdm/include
 
 source ${INCLUDE}/mdm-debug.inc
 source ${INCLUDE}/mdm-path.inc
 source ${INCLUDE}/mdm-hardware.inc
 source ${INCLUDE}/mdm-xephyr.inc
 source ${INCLUDE}/mdm-links.inc
 source ${INCLUDE}/mdm-images.inc
 source ${INCLUDE}/mdm-execute.inc

#
# Main Function

function Main()
{

    CallXephyr ${@}
    
} # Main
 
 
# Script entry point

    Main ${@}
    
    exit 0

