#! /bin/bash
#
# Copyright (C) 2004-2008 Centro de Computacao Cientifica e Software Livre
# Departamento de Informatica - Universidade Federal do Parana - C3SL/UFPR
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,
# USA.

#  A funcão deste script é carregar o Xephyr. Ele pode ser chamado
#  para fazer uma de duas funcões:
#       * chamar diretamente o script que chama o Xephyr
#       * chamar indiretamente o script que chama o Xephyr, através da
#         funcão OpenTerminal. Este recurso é usado pq é preciso manter
#         um script rodando em segundo plano para cada uma das cabecas
#         do terminal. Para maiores informacões, veja a funcão OpenTerminal
#         no arquivo mdm-execute.inc
#

#**********************************
#  Script Version: 1.0.1
#                  27/02/2008
#
#  Dependencies:
#       mdm-path.inc
#       mdm-debug.inc
#       mdm-images.inc
#       mdm-execute.inc
#       mdm-xephyr.inc
#       mdm-links.inc
#       mdm.conf
 
 INCLUDE=/usr/share/mdm/include
 
 source ${INCLUDE}/mdm-debug.inc
 source ${INCLUDE}/mdm-path.inc
 source ${INCLUDE}/mdm-hardware.inc
 source ${INCLUDE}/mdm-xephyr.inc
 source ${INCLUDE}/mdm-links.inc
 source ${INCLUDE}/mdm-images.inc
 source ${INCLUDE}/mdm-execute.inc

#
# Funcao Principal 

function Main()
{

    CallXephyr ${@}
    
} # Main
 
 
# Ponto de entrada do script

    Main ${@}
    
    exit 0

