#! /bin/bash

# Copyright (C) 2004-2007 Centro de Computacao Cientifica e Software Livre
# Departamento de Informatica - Universidade Federal do Parana - C3SL/UFPR
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,
# USA.

#
# This script makes the mdm post installation configurations 
#

#**********************************
#
#  File Version: 1.0.1
#                04/03/2008 

RESP=""
while [[ "${RESP}" != "y" && "${RESP}" != "n" ]]; do
    echo -n -e "\nSet init.d automatic scripts? "
    read RESP
done

if [[ ${RESP} == "y" ]]; then
    # sets automatic initialization of xorg.conf creator
    update-rc.d mdm-create start 12 2 3 4 5 . 

    # sets gdm automatic initialization
    update-rc.d mdm-init start 97 2 3 4 5 . stop 97 0 1 6 . 
fi
