#! /bin/bash

# Copyright (C) 2004-2007 Centro de Computacao Cientifica e Software Livre
# Departamento de Informatica - Universidade Federal do Parana - C3SL/UFPR
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,
# USA.

#
# This script makes system cleaning after uninstallation
#

#**********************************
#
#  File Version: 1.0.1
#                04/03/2008 

X11=/etc/X11
TMP=/tmp/mdm
LOG=/var/log/mdm
PIDS=/var/run/mdm
GDM=/etc/gdm
KBD=/usr/share/X11/xkb

# remove create-xorg-conf from automatic execution
update-rc.d -f mdm-create remove 

# remove mdm from automatic execution
update-rc.d -f mdm-init remove

# restore original gdm.conf
dpkg-divert --package multiseat-xephyr --rename --remove ${GDM}/gdm.conf

# restore original evdev
dpkg-divert --package multiseat-xephyr --rename --remove ${KBD}/keycodes/evdev

# remove xorg.conf.mdm
if [[ -f ${X11}/xorg.conf.mdm ]]; then
    rm -f ${X11}/xorg.conf.mdm
fi

# remove temporary directories
if [[ -d ${TMP} ]]; then
    rm -r -f ${TMP}
fi

# remove log directory
if [[ -d ${LOG} ]]; then
    rm -r -f ${LOG}
fi

# remove PIDs directory
if [[ -d ${PIDS} ]]; then
    rm -r -f ${PIDS}
fi


