#! /bin/bash

# Copyright (C) 2004-2007 Centro de Computacao Cientifica e Software Livre
# Departamento de Informatica - Universidade Federal do Parana - C3SL/UFPR
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,
# USA.

#
# Este script executa uma preparacão para a instalacão do sistema mdm.
#

#**********************************
#
#  File Version: 1.0.1
#                04/03/2008 

set -e 

GDM=/etc/gdm
KBD=/usr/share/X11/xkb

# Backup gdm.conf
cp ${GDM}/gdm.conf ${GDM}/gdm.conf.mdm

# Backup original configuration
dpkg-divert --package multiseat-xephyr --add --rename \
            --divert ${GDM}/gdm.conf.mdm.real ${GDM}/gdm.conf
dpkg-divert --package multiseat-xephyr --add --rename \
            --divert ${KBD}/keycodes/evdev.mdm.real ${KBD}/keycodes/evdev
