#! /bin/sh

# Copyright (C) 2004-2007 Centro de Computacao Cientifica e Software Livre
# Departamento de Informatica - Universidade Federal do Parana - C3SL/UFPR
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,
# USA.

GDM=/etc/gdm
X11=/etc/X11
XKB=/usr/share/X11/xkb

#configura a inicialização automática do criador do xorg.conf
#update-rc.d -f create_xorg_conf remove 
#configura a inicialização automática do gerenciador mdm
#update-rc.d -f mdm remove 
#dpkg-divert --package multiseat-xephyr --rename --remove $GDM/gdm.conf
dpkg-divert --package prd-multiterminal --rename --remove $XKB/keycodes/evdev
if [ -f $X11/xorg.conf.mdm ]; then
    rm $X11/xorg.conf.mdm
fi

if [ -f /export/configs/multiterminais/geral/etc/rc2.d/S12create_xorg_conf ]; then
    rm -f /export/configs/multiterminais/geral/etc/rc2.d/S12create_xorg_conf
fi
if [ -f /export/configs/multiterminais/geral/etc/rc2.d/S97mdm ]; then
    rm -f /export/configs/multiterminais/geral/etc/rc2.d/S97mdm
fi

