#! /bin/sh

# Copyright (C) 2004-2007 Centro de Computacao Cientifica e Software Livre
# Departamento de Informatica - Universidade Federal do Parana - C3SL/UFPR
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,
# USA.

# configura a inicialização automática do criador do xorg.conf
ln -sf /etc/init.d/create_xorg_conf /export/configs/multiterminais/geral/etc/rc2.d/S12create_xorg_conf 
ln -sf /etc/init.d/mdm /export/configs/multiterminais/geral/etc/rc2.d/S97mdm

#update-rc.d create_xorg_conf start 12 2 3 4 5 . 
# configura a inicialização automática do gerenciador mdm
#update-rc.d mdm start 97 2 3 4 5 . stop 97 0 1 6 . 
