#!/bin/bash

# Copyright (C) 2004-2007 Centro de Computacao Cientifica e Software Livre
# Departamento de Informatica - Universidade Federal do Parana - C3SL/UFPR
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301,
# USA.

MDM_PREFIX=/
MDM_SCRIPTS=${MDM_PREFIX}/usr/sbin

while (( $# > 0 )); do
    case "$1" in
        -xauthority)
            export XAUTHORITY=$2
            shift 2
            ;;
        -display)
            export DISPLAY=$2
            shift 2
            ;;
        *)
            XEPHYR_ARGS="$XEPHYR_ARGS $1"
            shift 1
            ;;
    esac
done

exec Xephyr $XEPHYR_ARGS
                                                                                                
